### ISSUE TITLE
man pages cannot be build from PyPI source

### ISSUE THREAD

**Issue by penguinpee** [nih-at/nihtest#1]
I'm busy packaging `nihtest` for Fedora. When trying to build the man pages, I discovered that the Makefile is missing from the PyPI tarball:

```
pushd manpages
make
~/build/BUILD/nihtest-1.1.0/manpages ~/build/BUILD/nihtest-1.1.0
make: *** No targets specified and no makefile found.  Stop.
```

Could that Makefile be shipped with the PyPI tarball?

I can use the GitHub sources for now, but I'd prefer using the PyPI sources.

**Comment by 0-wiz-0** [comment]
The Makefile generates the `.man` and `.html` formats from the master `.mdoc` format.
The pypi distfile contains all three file formats, so you don't need the `Makefile` - just install the version that's most appropriate for your operating system.

**Comment by penguinpee** [comment]
Not re-opening, since what you say is correct.

But in packaging we have the tendency to build everything from scratch. That is required for binaries, but also recommended for documentation. So, instead of using what's there, I'd like to be able to generate it myself. There's no harm in shipping the `Makefile` is there? Consider it a _nice to have_ kinda RFE.

**Comment by bkmgit** [comment]
Using the source distributed on GitHub, one can regenerate the documentation by going into the manpages directory and typing `make` provided the mandoc package is available.

**Comment by penguinpee** [comment]
Yes. That's what I'm currently doing. But, as I mentioned in my opening post, I prefer using PyPI sources. And that is missing the Makefile.

**Comment by 0-wiz-0** [comment]
Ok, it's a small file - added.

**Comment by penguinpee** [comment]
:+1: Thanks!
