### ISSUE TITLE
Can get a build error since pymodules not explicitly listed

### ISSUE THREAD

**Issue by bkmgit** [nih-at/nihtest#2]
https://stackoverflow.com/questions/72294299/multiple-top-level-packages-discovered-in-a-flat-layout

**Comment by 0-wiz-0** [comment]
What error exactly are you seeing, when you build in what way?

**Comment by bkmgit** [comment]
Sorry, seems to be a packaging issue:
https://github.com/rpm-software-management/rpm/issues/2532
https://download.copr.fedorainfracloud.org/results/gui1ty/reviews/fedora-rawhide-x86_64/06112141-python-nihtest/python-nihtest.spec
