### ISSUE TITLE
preload-pass.test fails with glibc

### ISSUE THREAD

**Issue by miller-alex** [nih-at/nihtest#7]
Running the test suite of nihtest 1.5.0 on linux/glibc results in one failed test case, preload-pass.test. This test can cannot possibly work since glibc uses symbol versioning and the preloaded library defines an unversioned symbol:
```
> nm -D nihtest-file | grep remove
                 U remove@GLIBC_2.2.5
> nm -D libineffective-remove.so | grep remove
0000000000001110 T remove
```
But `remove@GLIBC_2.2.5` in `nihtest-file` obviously doesn't bind to the unversioned `remove` from the preloaded library.

**Comment by 0-wiz-0** [comment]
Do you know a symbol we could use instead?
Does 'remove@@' work?

**Comment by miller-alex** [comment]
No, `remove@@` doesn't help. The symbol versions have to match exactly, or the symbol from the preloaded library will not be considered.

In this case it gets a little complicated because different libcs (in case of glibc even different (sub)archs) use different symbol versions (or none). So I guess you have to check what version gets actually used:
* Link `nihtest-file` before `libineffective-remove.so`.
* List its dynamic symbols, e.g. with `nm -D nihtest-file`.
* Find the symbol you want to override (i.e. `remove`) and extract the symbol version, if any.
* If the symbol has a version suffix, then link `libineffective-remove.so` with a version script that sets the expected symbol version.

Alternatively, you could search for the default version of `remove` in libc, i.e. the one with `@@` in the name (there is no other version in my libc, though). That is slightly more complicated (you have to find the correct libc) but could be done in the configure step.

The version script should look like `@REMOVE_VER@ { global: remove; };` where `@REMOVE_VER@` is to be replaced by the expected symbol version. For example, on my system, where `nihtest-file` has an undefind symbol `remove@GLIBC_2.2.5`, 
the version script becomes `GLIBC_2.2.5 { global: remove; };`.
Pass the version script to the linker with `-Wl,--version-script=libineffective-remove.map` assuming the version script file name is `libineffective-remove.map`.

I don't know whether cmake provides support that can simplify the task.

See https://sourceware.org/binutils/docs/ld/VERSION.html for basic info on symbol versions and linker scripts or https://www.akkadia.org/drepper/dsohowto.pdf for more background.

**Comment by 0-wiz-0** [comment]
I took a different route - in the test we're not really interested in if we can override a libc symbol, it's enough if we can override a symbol from a library. So I made a library and overrode its symbol.
Please verify that this fixes the problem for you too!
